# IPTV Playlist Generator Configuration
general:
  source_file: sources.txt
  output_file: playlist.m3u
  output_epg: epg.xml.gz
  epg_base_url: https://github.com/hoangxg4/mix-iptv/releases/latest/download
  timeout: 10
  stream_timeout: 3
  max_workers: 64
  epg_trim_days: 7
  spam_keywords: []

cache:
  enabled: true
  dir: .cache
  epg_ttl: 3600
  source_ttl: 300
  link_ttl: 600

proxy:
  enabled: true
  socks5: socks5://proxy:999999@tele1gbps.90s.one:9999
