name: Update IPTV Playlist

on:
  schedule:
    # Chạy tự động mỗi 12 tiếng
    - cron: '0 */6 * * *'
  
  workflow_dispatch: # Cho phép bấm nút chạy thủ công
  
  push:
    paths:
      - 'sources.txt' # Tự động chạy khi file này có thay đổi

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run merge and EPG trim script
        run: python main.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Auto-update playlist, EPG & update source status [skip ci]"
          # Đã bổ sung đầy đủ 3 file cần update
          file_pattern: "playlist.m3u light_epg.xml sources.txt"
